// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmitenightApp.Persistence;

#nullable disable

namespace SmitenightApp.Persistence.Migrations
{
    [DbContext(typeof(SmitenightDbContext))]
    [Migration("20220729165544_Adjustments_to_Actives_and_Root_Id")]
    partial class Adjustments_to_Actives_and_Root_Id
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SmitenightApp.Domain.Models.Abilities.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AbilityType")
                        .HasColumnType("int");

                    b.Property<string>("Cooldown")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GodId")
                        .HasColumnType("int");

                    b.Property<int>("SmiteId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GodId");

                    b.ToTable("Abilities", (string)null);
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Abilities.AbilityRank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AbilityId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId");

                    b.ToTable("AbilityRanks", (string)null);
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Abilities.AbilityTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AbilityId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId");

                    b.ToTable("AbilityTags", (string)null);
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Gods.BasicAttackDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GodId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GodId");

                    b.ToTable("BasicAttackDescriptions", (string)null);
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Gods.God", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<float>("AttackSpeed")
                        .HasColumnType("real");

                    b.Property<float>("AttackSpeedPerLevel")
                        .HasColumnType("real");

                    b.Property<bool>("AutoBanned")
                        .HasColumnType("bit");

                    b.Property<string>("GodCardUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GodIconUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("HealthPerFive")
                        .HasColumnType("int");

                    b.Property<int>("HealthPerLevel")
                        .HasColumnType("int");

                    b.Property<float>("Hp5PerLevel")
                        .HasColumnType("real");

                    b.Property<bool>("LatestGod")
                        .HasColumnType("bit");

                    b.Property<string>("Lore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("MagicProtection")
                        .HasColumnType("real");

                    b.Property<float>("MagicProtectionPerLevel")
                        .HasColumnType("real");

                    b.Property<int>("MagicalPower")
                        .HasColumnType("int");

                    b.Property<float>("MagicalPowerPerLevel")
                        .HasColumnType("real");

                    b.Property<int>("Mana")
                        .HasColumnType("int");

                    b.Property<float>("ManaPerFive")
                        .HasColumnType("real");

                    b.Property<int>("ManaPerLevel")
                        .HasColumnType("int");

                    b.Property<float>("Mp5PerLevel")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OnFreeRotation")
                        .HasColumnType("bit");

                    b.Property<string>("Pantheon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhysicalPower")
                        .HasColumnType("int");

                    b.Property<float>("PhysicalPowerPerLevel")
                        .HasColumnType("real");

                    b.Property<float>("PhysicalProtection")
                        .HasColumnType("real");

                    b.Property<float>("PhysicalProtectionPerLevel")
                        .HasColumnType("real");

                    b.Property<string>("Pros")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("SmiteId")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Gods", (string)null);
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Gods.GodBan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("GodBanOrder")
                        .HasColumnType("int");

                    b.Property<int>("GodId")
                        .HasColumnType("int");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GodId");

                    b.HasIndex("MatchId");

                    b.ToTable("GodBans", (string)null);
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Gods.GodSkin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("GodId")
                        .HasColumnType("int");

                    b.Property<string>("GodSkinUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Obtainability")
                        .HasColumnType("int");

                    b.Property<int>("PriceFavor")
                        .HasColumnType("int");

                    b.Property<int>("PriceGems")
                        .HasColumnType("int");

                    b.Property<int>("SecondarySmiteId")
                        .HasColumnType("int");

                    b.Property<int>("SmiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GodId");

                    b.ToTable("GodSkins", (string)null);
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Items.Active", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ChildActiveId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("ItemIconUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemTier")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("RootActiveId")
                        .HasColumnType("int");

                    b.Property<string>("SecondaryDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SmiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChildActiveId");

                    b.HasIndex("RootActiveId");

                    b.ToTable("Actives", (string)null);
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Items.ActivePurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ActiveId")
                        .HasColumnType("int");

                    b.Property<int>("ActivePurchaseOrder")
                        .HasColumnType("int");

                    b.Property<int>("MatchDetailId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActiveId");

                    b.HasIndex("MatchDetailId");

                    b.ToTable("ActivePurchases", (string)null);
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Items.Consumable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("ItemIconUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("SecondaryDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SmiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Consumables", (string)null);
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Items.ConsumableDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ConsumableId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumableId");

                    b.ToTable("ConsumableDescriptions", (string)null);
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Items.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ChildItemId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<bool>("Glyph")
                        .HasColumnType("bit");

                    b.Property<string>("ItemIconUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemTier")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("RestrictedRoles")
                        .HasColumnType("int");

                    b.Property<int?>("RootItemId")
                        .HasColumnType("int");

                    b.Property<string>("SecondaryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SmiteId")
                        .HasColumnType("int");

                    b.Property<bool>("StartingItem")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ChildItemId");

                    b.HasIndex("RootItemId");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Items.ItemDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemDescriptions", (string)null);
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Items.ItemPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("ItemPurchaseOrder")
                        .HasColumnType("int");

                    b.Property<int>("MatchDetailId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("MatchDetailId");

                    b.ToTable("ItemPurchases", (string)null);
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Matches.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("GameMap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameModeQueue")
                        .HasColumnType("int");

                    b.Property<int>("MatchDuration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SmiteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeamOneScore")
                        .HasColumnType("int");

                    b.Property<int>("TeamTwoScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Matches", (string)null);
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Matches.MatchDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Assists")
                        .HasColumnType("int");

                    b.Property<int>("BotKills")
                        .HasColumnType("int");

                    b.Property<int>("DamageDone")
                        .HasColumnType("int");

                    b.Property<int>("DamageDoneInHand")
                        .HasColumnType("int");

                    b.Property<int>("DamageDoneMagical")
                        .HasColumnType("int");

                    b.Property<int>("DamageDonePhysical")
                        .HasColumnType("int");

                    b.Property<int>("DamageDoneToBots")
                        .HasColumnType("int");

                    b.Property<int>("DamageDoneToStructures")
                        .HasColumnType("int");

                    b.Property<int>("DamageMitigated")
                        .HasColumnType("int");

                    b.Property<int>("DamageTaken")
                        .HasColumnType("int");

                    b.Property<int>("DamageTakenMagical")
                        .HasColumnType("int");

                    b.Property<int>("DamageTakenPhysical")
                        .HasColumnType("int");

                    b.Property<int>("Deaths")
                        .HasColumnType("int");

                    b.Property<int>("DistanceTraveled")
                        .HasColumnType("int");

                    b.Property<int>("DoubleKills")
                        .HasColumnType("int");

                    b.Property<int>("FireGiantKills")
                        .HasColumnType("int");

                    b.Property<int>("FirstBlood")
                        .HasColumnType("int");

                    b.Property<int>("GodId")
                        .HasColumnType("int");

                    b.Property<int>("GodRole")
                        .HasColumnType("int");

                    b.Property<int>("GodSkinId")
                        .HasColumnType("int");

                    b.Property<int>("GoldEarned")
                        .HasColumnType("int");

                    b.Property<int>("GoldEarnedPerMinute")
                        .HasColumnType("int");

                    b.Property<int>("GoldFuryKills")
                        .HasColumnType("int");

                    b.Property<int>("HealingDone")
                        .HasColumnType("int");

                    b.Property<int>("HealingDoneToBots")
                        .HasColumnType("int");

                    b.Property<int>("HealingDoneToSelf")
                        .HasColumnType("int");

                    b.Property<int>("HighestMultiKill")
                        .HasColumnType("int");

                    b.Property<int>("KillingSpree")
                        .HasColumnType("int");

                    b.Property<int>("LevelReached")
                        .HasColumnType("int");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("MatchTeam")
                        .HasColumnType("int");

                    b.Property<int>("ObjectiveAssists")
                        .HasColumnType("int");

                    b.Property<int>("PartyId")
                        .HasColumnType("int");

                    b.Property<int>("PentaKills")
                        .HasColumnType("int");

                    b.Property<int>("PhoenixKills")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerKills")
                        .HasColumnType("int");

                    b.Property<int>("QuadraKills")
                        .HasColumnType("int");

                    b.Property<int>("SiegeJuggernautKills")
                        .HasColumnType("int");

                    b.Property<int>("SingleKills")
                        .HasColumnType("int");

                    b.Property<bool>("Surrendered")
                        .HasColumnType("bit");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("TotalTimeDead")
                        .HasColumnType("int");

                    b.Property<int>("TowerKills")
                        .HasColumnType("int");

                    b.Property<int>("TripleKills")
                        .HasColumnType("int");

                    b.Property<int>("WardsPlaced")
                        .HasColumnType("int");

                    b.Property<int>("WildJuggernautKills")
                        .HasColumnType("int");

                    b.Property<bool>("Winner")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GodId");

                    b.HasIndex("GodSkinId");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("MatchDetails", (string)null);
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Players.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("HirezPlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MasteryLevel")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PortalType")
                        .HasColumnType("int");

                    b.Property<int>("SmiteId")
                        .HasColumnType("int");

                    b.Property<int?>("SmitePortalUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Teams.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SmiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Abilities.Ability", b =>
                {
                    b.HasOne("SmitenightApp.Domain.Models.Gods.God", "God")
                        .WithMany("Abilities")
                        .HasForeignKey("GodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("God");
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Abilities.AbilityRank", b =>
                {
                    b.HasOne("SmitenightApp.Domain.Models.Abilities.Ability", "Ability")
                        .WithMany("AbilityRanks")
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Abilities.AbilityTag", b =>
                {
                    b.HasOne("SmitenightApp.Domain.Models.Abilities.Ability", "Ability")
                        .WithMany("AbilityTags")
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Gods.BasicAttackDescription", b =>
                {
                    b.HasOne("SmitenightApp.Domain.Models.Gods.God", "God")
                        .WithMany("BasicAttackDescriptions")
                        .HasForeignKey("GodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("God");
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Gods.GodBan", b =>
                {
                    b.HasOne("SmitenightApp.Domain.Models.Gods.God", "God")
                        .WithMany("GodBans")
                        .HasForeignKey("GodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmitenightApp.Domain.Models.Matches.Match", "Match")
                        .WithMany("GodBans")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("God");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Gods.GodSkin", b =>
                {
                    b.HasOne("SmitenightApp.Domain.Models.Gods.God", "God")
                        .WithMany("GodSkins")
                        .HasForeignKey("GodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("God");
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Items.Active", b =>
                {
                    b.HasOne("SmitenightApp.Domain.Models.Items.Active", "ChildActive")
                        .WithMany()
                        .HasForeignKey("ChildActiveId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SmitenightApp.Domain.Models.Items.Active", "RootActive")
                        .WithMany()
                        .HasForeignKey("RootActiveId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChildActive");

                    b.Navigation("RootActive");
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Items.ActivePurchase", b =>
                {
                    b.HasOne("SmitenightApp.Domain.Models.Items.Active", "Active")
                        .WithMany("ActivePurchases")
                        .HasForeignKey("ActiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmitenightApp.Domain.Models.Matches.MatchDetail", "MatchDetail")
                        .WithMany("ActivePurchases")
                        .HasForeignKey("MatchDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Active");

                    b.Navigation("MatchDetail");
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Items.ConsumableDescription", b =>
                {
                    b.HasOne("SmitenightApp.Domain.Models.Items.Consumable", "Consumable")
                        .WithMany("ConsumableDescriptions")
                        .HasForeignKey("ConsumableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consumable");
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Items.Item", b =>
                {
                    b.HasOne("SmitenightApp.Domain.Models.Items.Item", "ChildItem")
                        .WithMany()
                        .HasForeignKey("ChildItemId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SmitenightApp.Domain.Models.Items.Item", "RootItem")
                        .WithMany()
                        .HasForeignKey("RootItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChildItem");

                    b.Navigation("RootItem");
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Items.ItemDescription", b =>
                {
                    b.HasOne("SmitenightApp.Domain.Models.Items.Item", "Item")
                        .WithMany("ItemDescriptions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Items.ItemPurchase", b =>
                {
                    b.HasOne("SmitenightApp.Domain.Models.Items.Item", "Item")
                        .WithMany("ItemPurchases")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmitenightApp.Domain.Models.Matches.MatchDetail", "MatchDetail")
                        .WithMany("ItemPurchases")
                        .HasForeignKey("MatchDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("MatchDetail");
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Matches.MatchDetail", b =>
                {
                    b.HasOne("SmitenightApp.Domain.Models.Gods.God", "God")
                        .WithMany("MatchDetails")
                        .HasForeignKey("GodId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SmitenightApp.Domain.Models.Gods.GodSkin", "GodSkin")
                        .WithMany("MatchDetails")
                        .HasForeignKey("GodSkinId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SmitenightApp.Domain.Models.Matches.Match", "Match")
                        .WithMany("MatchDetails")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmitenightApp.Domain.Models.Players.Player", "Player")
                        .WithMany("MatchDetails")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SmitenightApp.Domain.Models.Teams.Team", "Team")
                        .WithMany("MatchDetails")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("God");

                    b.Navigation("GodSkin");

                    b.Navigation("Match");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Abilities.Ability", b =>
                {
                    b.Navigation("AbilityRanks");

                    b.Navigation("AbilityTags");
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Gods.God", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("BasicAttackDescriptions");

                    b.Navigation("GodBans");

                    b.Navigation("GodSkins");

                    b.Navigation("MatchDetails");
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Gods.GodSkin", b =>
                {
                    b.Navigation("MatchDetails");
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Items.Active", b =>
                {
                    b.Navigation("ActivePurchases");
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Items.Consumable", b =>
                {
                    b.Navigation("ConsumableDescriptions");
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Items.Item", b =>
                {
                    b.Navigation("ItemDescriptions");

                    b.Navigation("ItemPurchases");
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Matches.Match", b =>
                {
                    b.Navigation("GodBans");

                    b.Navigation("MatchDetails");
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Matches.MatchDetail", b =>
                {
                    b.Navigation("ActivePurchases");

                    b.Navigation("ItemPurchases");
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Players.Player", b =>
                {
                    b.Navigation("MatchDetails");
                });

            modelBuilder.Entity("SmitenightApp.Domain.Models.Teams.Team", b =>
                {
                    b.Navigation("MatchDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
