namespace Smitenight.Providers.SmiteProvider.Contracts.Models.RetrievePlayerClient
{
    public record class PlayerDto
    (
        int ActivePlayerId,
        string AvatarUrl,
        string CreatedDatetime,
        int HoursPlayed,
        int Id,
        string LastLoginDatetime,
        int Leaves,
        int Level,
        int Losses,
        int MasteryLevel,
        object MergedPlayers,
        int MinutesPlayed,
        string Name,
        string PersonalStatusMessage,
        string Platform,
        float RankStatConquest,
        float RankStatConquestController,
        float RankStatDuel,
        float RankStatDuelController,
        float RankStatJoust,
        float RankStatJoustController,
        RankedDetailsDto RankedConquest,
        RankedDetailsDto RankedConquestController,
        RankedDetailsDto RankedDuel,
        RankedDetailsDto RankedDuelController,
        RankedDetailsDto RankedJoust,
        RankedDetailsDto RankedJoustController,
        string Region,
        int TeamId,
        string TeamName,
        int TierConquest,
        int TierDuel,
        int TierJoust,
        int TotalAchievements,
        int TotalWorshippers,
        int Wins,
        string HzGamerTag,
        string HzPlayerName,
        object RetMsg
    );

    public record class RankedDetailsDto
    (
        int Leaves,
        int Losses,
        string Name,
        int Points,
        int PrevRank,
        int Rank,
        float RankStat,
        object RankStatConquest,
        object RankStatJoust,
        int RankVariance,
        int Round,
        int Season,
        int Tier,
        int Trend,
        int Wins,
        object PlayerId,
        object RetMsg
    );
}