namespace Smitenight.Providers.SmiteProvider.Contracts.Models.PlayerClient;

public record class MatchHistoryDto
{
    public required int ActiveId1 { get; init; }
    public required int ActiveId2 { get; init; }
    public required string Active1 { get; init; }
    public required string Active2 { get; init; }
    public string? Active3 { get; init; }
    public required int Assists { get; init; }
    public required string Ban1 { get; init; }
    public required string Ban10 { get; init; }
    public required int Ban10Id { get; init; }
    public required string Ban11 { get; init; }
    public required int Ban11Id { get; init; }
    public required string Ban12 { get; init; }
    public required int Ban12Id { get; init; }
    public required int Ban1Id { get; init; }
    public required string Ban2 { get; init; }
    public required int Ban2Id { get; init; }
    public required string Ban3 { get; init; }
    public required int Ban3Id { get; init; }
    public required string Ban4 { get; init; }
    public required int Ban4Id { get; init; }
    public required string Ban5 { get; init; }
    public required int Ban5Id { get; init; }
    public required string Ban6 { get; init; }
    public required int Ban6Id { get; init; }
    public required string Ban7 { get; init; }
    public required int Ban7Id { get; init; }
    public required string Ban8 { get; init; }
    public required int Ban8Id { get; init; }
    public required string Ban9 { get; init; }
    public required int Ban9Id { get; init; }
    public required int Creeps { get; init; }
    public required int Damage { get; init; }
    public required int DamageBot { get; init; }
    public required int DamageDoneInHand { get; init; }
    public required int DamageMitigated { get; init; }
    public required int DamageStructure { get; init; }
    public required int DamageTaken { get; init; }
    public required int DamageTakenMagical { get; init; }
    public required int DamageTakenPhysical { get; init; }
    public required int Deaths { get; init; }
    public required int DistanceTraveled { get; init; }
    public required string FirstBanSide { get; init; }
    public required string God { get; init; }
    public required int GodId { get; init; }
    public required int Gold { get; init; }
    public required int Healing { get; init; }
    public required int HealingBot { get; init; }
    public required int HealingPlayerSelf { get; init; }
    public required int ItemId1 { get; init; }
    public required int ItemId2 { get; init; }
    public required int ItemId3 { get; init; }
    public required int ItemId4 { get; init; }
    public required int ItemId5 { get; init; }
    public required int ItemId6 { get; init; }
    public required string Item1 { get; init; }
    public required string Item2 { get; init; }
    public required string Item3 { get; init; }
    public required string Item4 { get; init; }
    public required string Item5 { get; init; }
    public required string Item6 { get; init; }
    public required int KillingSpree { get; init; }
    public required int Kills { get; init; }
    public required int Level { get; init; }
    public required string MapGame { get; init; }
    public required int Match { get; init; }
    public required int MatchQueueId { get; init; }
    public required string MatchTime { get; init; }
    public required int Minutes { get; init; }
    public required int MultiKillMax { get; init; }
    public required int ObjectiveAssists { get; init; }
    public required string Queue { get; init; }
    public required string Region { get; init; }
    public required string Role { get; init; }
    public required string Skin { get; init; }
    public required int SkinId { get; init; }
    public required int Surrendered { get; init; }
    public required int TaskForce { get; init; }
    public required int Team1Score { get; init; }
    public required int Team2Score { get; init; }
    public required int TimeInMatchSeconds { get; init; }
    public required int WardsPlaced { get; init; }
    public required string WinStatus { get; init; }
    public required int WinningTaskForce { get; init; }
    public required int PlayerId { get; init; }
    public required string PlayerName { get; init; }
    public string? RetMsg { get; init; }
}
