name: Deploy DotNet project to function app with a Linux environment

on:
  push:
    branches: [ main, test_function ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP_CREDENTIALS }}

    - name: 'Login on Azure Container Registry'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/stopsmitenight:${{ github.sha }} -f ./SmitenightApp/SmitenightApp.Function.StopSmitenight/Dockerfile .
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/stopsmitenight:${{ github.sha }}

    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-container-action@v1
      with:
        app-name: 'func-stopsmitenight-dev-001'
        image: '${{ secrets.REGISTRY_LOGIN_SERVER }}/stopsmitenight:${{ github.sha }}'

    - name: 'Azure logout'
      run: |
        az logout